// <auto-generated />
using energy_bill.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace energy_bill.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171020023807_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("energy_bill.Models.BillEnergy", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("avgComsumption");

                    b.Property<DateTime>("datePayment");

                    b.Property<DateTime>("dateRead");

                    b.Property<int>("kwSpent");

                    b.Property<int>("numberRead");

                    b.Property<double>("price");

                    b.HasKey("id");

                    b.ToTable("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
